---
title: "MICB425 Portfolio - Microbial Ecological Genomics: From Genomes to Biomes, Spring 2018"
author: "Jinsong, Tony, Yan, 18752148"
date: "Version 1.0 (January 19, 2018)"
output: html_document
---

# Module 01
Reserve the first level headings (#) for the start of a new Module. This will help to organize your portfolio in an intuitive fashion.  

## Module 01 portfolio check
The first of your second level headers (##) is to be used for the portfolio content checks. The Module 01 portfolio check has been built for you directly into this template, but will also be available as a stand-alone markdown document available on the MICB425 GitHub so that you know what is required in each module section in your portfolio. The completion status and comments will be filled in by the instructors during portfolio checks when your current portfolios are pulled from GitHub.

* Installation check
    + Completion status:
    + Comments:
* Portfolio repo setup
    + Completion status: 
    + Comments:
* RMarkdown Pretty html Challenge
    + Completion status:
    + Comments:
* Evidence worksheet_01
    + Completion status:
    + Comments:
* Evidence worksheet_02
    + Completion status:
    + Comments:
* Evidence worksheet_03
    + Completion status:
    + Comments:
* Problem Set_01
    + Completion status:
    + Comments:
* Problem Set_02
    + Completion status:
    + Comments:
* Writing assessment_01
    + Completion status:
    + Comments:
* Additional Readings
    + Completion status:
    + Comments  
    
## Data science Friday  
The remaining second level headers (##) are for separating data science Friday, regular course, and project content. In this module, you will only need to include data science Friday and regular course content; projects will come later in the course.

### Installation check
Third level headers (###) should be used for links to assignments, evidence worksheets, problem sets, and readings, as seen here.  

Use this space to include your installation screenshots.



### Portfolio repo setup
Detail the code you used to create, initialize, and push your portfolio repo to GitHub. This will be helpful as you will need to repeat many of these steps to update your porfolio throughout the course.



### RMarkdown pretty html challenge
Paste your code from the in-class activity of recreating the example html.



## Origins and Earth Systems
### Evidence worksheet 01 
The template for the first Evidence Worksheet has been included here. The first thing for any assignment should link(s) to any relevant literature (which should be included as full citations in a module references section below).

You can copy-paste in the answers you recorded when working through the evidence worksheet into this portfolio template. 

As you include Evidence worksheets and Problem sets in the future, ensure that you delineate Questions/Learning Objectives/etc. by using headers that are 4th level and greater. This will still create header markings when you render (knit) the document, but will exclude these levels from the Table of Contents. That's a good thing. You don't' want to clutter the Table of Contents too much.

[Whitman *et al* 1998](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC33863/)

#### Learning objectives
Describe the numerical abundance of microbial life in relation to ecology and biogeochemistry of Earth systems. 

#### General questions
* What were the main questions being asked?  

* What were the primary methodological approaches used?  

* Summarize the main results or findings.  

* Do new questions arise from the results?  

* Were there any specific challenges or advantages in understanding the paper (*e.g.* did the authors provide sufficient background information to understand experimental logic, were methods explained adequately, were any specific assumptions made, were conclusions justified based on the evidence, were the figures or tables useful and easy to understand)?  



### Problem set 01
#### Learning objectives: 
Describe the numerical abundance of microbial life in relation to the ecology and biogeochemistry of Earth systems.

#### Specific questions:
* What are the primary prokaryotic habitats on Earth and how do they vary with respect to their capacity to support life? Provide a breakdown of total cell abundance for each primary habitat from the tables provided in the text.  

** (Answer): Marine environments (1.181x10^29) including polar water-ice interfaces, Soil (2.556x10^29), subsurface marine sediments (3.8x10^30), and microbiota. **

* What is the estimated prokaryotic cell abundance in the upper 200 m of the ocean and what fraction of this biomass is represented by marine cyanobacterium including Prochlorococcus? What is the significance of this ratio with respect to carbon cycling in the ocean and the atmospheric composition of the Earth?  

** (Answer): Upper 200m of ocean: Total number of cells = 3.6x10^28. Versus 2.9x10^27 for autotrophic prochlorococcus. Autotrophs have approximately 8% (4x10^4 / 5x10^5) of the total cell density for upper 200m ocean, meaning that carbon fixation makes up 80% of carbon cycling abundance in ocean, indicating a significant amount of the Earth's carbon dioxide is fixed through the ocean. **

* What is the difference between an autotroph, heterotroph, and a lithotroph based on information provided in the text?  

** (Answer): Autotroph: Fixes carbon from carbon dioxide gas. Heterotroph: Uses carbon from organic compounds. Lithotroph: Uses inorganic substances (like minerals) to obtain reducing agents. **

* Based on information provided in the text and your knowledge of geography what is the deepest habitat capable of supporting prokaryotic life? What is the primary limiting factor at this depth?  

** (Answer): Deep habitats supporting life, subsurface separated into terrestrial and marine. Temperature is limiting factor at very high depths in Mariana Trench (10.9km). **

* Based on information provided in the text your knowledge of geography what is the highest habitat capable of supporting prokaryotic life? What is the primary limiting factor at this height?  

** (Answer): Qualities of air and atmosphere at that environment (Mt Everest 8.8km) also affects growth capabilities. **

* Based on estimates of prokaryotic habitat limitation, what is the vertical distance of the Earth’s biosphere measured in km?  

** (Answer): 24km from the highest point to the lowester point on Earth represents the general biosphere. **

* How was annual cellular production of prokaryotes described in Table 7 column four determined? (Provide an example of the calculation)  

** (Answer): Population x turnover/yr = cells/yr. e.g. marine heteros -> [3.6x10^28 cells x 365 days]/16 turnovers = 8.2x10^29 cells/yr. Virus affect growth and turnover rate and may contain metabolic assessory genes that can reprogram cells metabolically. **

* What is the relationship between carbon content, carbon assimilation efficiency and turnover rates in the upper 200m of the ocean? Why does this vary with depth in the ocean and between terrestrial and marine habitats?  

** (Answer): Carbon Efficiency = 20%  5-20fg C/cell 10x10^-30 pg/Cell  (3.6x10^28 Cells)x(10x10^-30 pg/cell)= 0.72 Pg carbonin marine heteros. 4x0.72= 2.88 Pg/yr of C. 51 Pg C/yr w/ 85% consumed = 43 Pg C/yr (43 Pg C/yr)/(2.88 Pg/yr) = 14.9, 1 turnover every 24.5 days. **

* How were the frequency numbers for four simultaneous mutations in shared genes determined for marine heterotrophs and marine autotrophs given an average mutation rate of 4 x 10^-7^ per DNA replication? (Provide an example of the calculation with units. Hint: cell and generation cancel out)  

** (Answer): (4x10^-7 mutations/generation)^4 (simultaneous mutations) = 2.56x10^26 mutations/generation. 3.6x10^28 cells and 365/16=22.8 turnovers/yr. (3.6x10^28 x 22.8 = 8.2x10^29 Cells/yr x 2.56x10^-26 mutations/generation) = 2.1x10^4 mutations/yr. **

* Given the large population size and high mutation rate of prokaryotic cells, what are the implications with respect to genetic diversity and adaptive potential? Are point mutations the only way in which microbial genomes diversify and adapt? 

* What relationships can be inferred between prokaryotic abundance, diversity, and metabolic potential based on the information provided in the text? 



### Module 01 references
Utilize this space to include a bibliography of any literature you want associated with this module. We recommend keeping this as the final header under each module.

An example for Whitman and Wiebe (1998) has been included below.

Whitman WB, Coleman DC, and Wiebe WJ. 1998. Prokaryotes: The unseen majority. Proc Natl Acad Sci USA. 95(12):6578–6583.  [PMC33863](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC33863/)